name: "Hello World"
description: "Super cool hello world action"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
   outputs:
    time:
      description: "The time greeted you"
   runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{inputs.who-to-greet}}
